### ISSUE TITLE
请问一下，我是小白，这个代码是不是需要使用tensorflow-GPU版的跑，我的电脑没有显卡，不能跑，应该怎么办

### ISSUE THREAD

**Issue by lcq950818** [oscarhscc/Medical-NER#1]

**Comment by oscarhscc** [comment]
CPU版本的就好，不需要GPU
________________________________
寄件者: lcq950818 <notifications@github.com>
寄件日期: 2019年10月14日 21:29
收件者: oscarhscc/Medical-NER <Medical-NER@noreply.github.com>
副本: Subscribed <subscribed@noreply.github.com>
主旨: Re: [oscarhscc/Medical-NER] 请问一下，我是小白，这个代码是不是需要使用tensorflow-GPU版的跑，我的电脑没有显卡，不能跑，应该怎么办 (#1)


Closed #1<https://github.com/oscarhscc/Medical-NER/issues/1>.

―
